import * as React from "react";
import { P, Page } from "./Util";

export default () => (
  <Page bg="background" className="section">
    <P m={3} fontSize={3}>
      <strong>Generative Adversarial Networks</strong> comprise of two models:
      <ul>
        <li>
          The first model is the Generator (Gina) and it aims to generate new
          data similar to the expected one. The Generator could be assimilated
          to a human art forger, which creates fake works of art.
        </li>
        <li>
          The second model is the Discriminator (Dorothy). This model’s goal is
          to recognize if an input data is ‘real’ — belongs to the original
          dataset — or if it is ‘fake’ — generated by a forger. In this
          scenario, a Discriminator is analogous to the police (or an art
          expert), which tries to detect artworks as truthful or fraud.
        </li>
      </ul>
    </P>
  </Page>
);
